import { useState, useRef, useEffect } from "react";
import { Send, Sparkles, Loader2, MessageSquare } from "lucide-react";
import { api } from "../api";
import { Card } from "../components/UI";

const suggestedQuestions = [
  "Who owes me money?",
  "How much did I earn this month?",
  "What is my most profitable client?",
  "How many active missions do I have?",
  "Which invoices are overdue?",
];

export default function AssistantPage() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const endRef = useRef(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const sendMessage = async (text) => {
    const question = text || input.trim();
    if (!question || loading) return;

    const userMsg = { role: "user", content: question };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const data = await api.aiChat(question);
      setMessages((prev) => [...prev, { role: "ai", content: data.answer }]);
    } catch (err) {
      setMessages((prev) => [...prev, { role: "ai", content: null, error: err.message }]);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    sendMessage();
  };

  return (
    <div className="flex flex-col h-[calc(100vh-7rem)]">
      <Card className="flex flex-col flex-1 overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex items-center gap-2">
          <Sparkles size={20} className="text-indigo-500" />
          <h2 className="text-lg font-semibold text-gray-800">AI Assistant</h2>
          <span className="text-xs text-gray-400 ml-2">Ask questions about your freelance business</span>
        </div>

        {/* Messages area */}
        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
          {messages.length === 0 && (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <MessageSquare size={48} className="text-gray-200 mb-4" />
              <h3 className="text-lg font-medium text-gray-400 mb-2">How can I help you today?</h3>
              <p className="text-sm text-gray-400 mb-6">Ask me anything about your clients, missions, or invoices.</p>
              <div className="flex flex-wrap justify-center gap-2">
                {suggestedQuestions.map((q) => (
                  <button key={q} onClick={() => sendMessage(q)}
                    className="px-3 py-2 bg-indigo-50 text-indigo-700 rounded-lg text-sm hover:bg-indigo-100 transition-colors">
                    {q}
                  </button>
                ))}
              </div>
            </div>
          )}

          {messages.map((msg, i) => (
            <div key={i} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
              <div className={`max-w-[75%] rounded-2xl px-4 py-3 text-sm ${
                msg.role === "user"
                  ? "bg-indigo-600 text-white rounded-br-md"
                  : msg.error
                    ? "bg-red-50 text-red-700 border border-red-200 rounded-bl-md"
                    : "bg-gray-100 text-gray-800 rounded-bl-md"
              }`}>
                {msg.role === "ai" && !msg.error && (
                  <div className="flex items-center gap-1 mb-1">
                    <Sparkles size={12} className="text-indigo-400" />
                    <span className="text-xs font-medium text-indigo-500">AI</span>
                  </div>
                )}
                <p className="whitespace-pre-wrap">{msg.error || msg.content}</p>
                {msg.role === "ai" && !msg.error && (
                  <p className="text-xs text-gray-400 mt-2 italic">Generated by AI — review before sending</p>
                )}
              </div>
            </div>
          ))}

          {loading && (
            <div className="flex justify-start">
              <div className="bg-gray-100 rounded-2xl rounded-bl-md px-4 py-3">
                <div className="flex items-center gap-2 text-sm text-gray-500">
                  <Loader2 size={14} className="animate-spin" /> Thinking...
                </div>
              </div>
            </div>
          )}

          <div ref={endRef} />
        </div>

        {/* Input area */}
        <div className="border-t border-gray-100 px-6 py-4">
          <form onSubmit={handleSubmit} className="flex gap-2">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask about your business..."
              disabled={loading}
              className="flex-1 border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none disabled:opacity-50"
            />
            <button
              type="submit"
              disabled={loading || !input.trim()}
              className="bg-indigo-600 text-white px-4 py-2.5 rounded-lg hover:bg-indigo-700 disabled:opacity-50 transition-colors"
            >
              <Send size={18} />
            </button>
          </form>
        </div>
      </Card>
    </div>
  );
}
