import { useState, useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { ArrowLeft, Pencil, Trash2, Briefcase, FileText, Sparkles, Loader2 } from "lucide-react";
import { api } from "../api";
import { Spinner, ErrorMessage, StatusBadge, Card, Button, Modal } from "../components/UI";
import { useToast } from "../components/Toast";

export default function ClientDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const toast = useToast();
  const [client, setClient] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({});
  const [saving, setSaving] = useState(false);
  const [aiSummary, setAiSummary] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiError, setAiError] = useState(null);

  const generateSummary = async () => {
    setAiLoading(true);
    setAiError(null);
    try {
      const data = await api.aiSummarizeClient(parseInt(id));
      setAiSummary(data.summary);
    } catch (err) {
      setAiError(err.message);
    } finally {
      setAiLoading(false);
    }
  };

  const load = () => {
    setLoading(true);
    setError(null);
    api.getClient(id)
      .then((data) => { setClient(data); setForm(data); })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  };

  useEffect(load, [id]);

  const handleUpdate = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const updated = await api.updateClient(id, form);
      setClient({ ...client, ...updated });
      setEditing(false);
      toast.success("Client updated");
    } catch (err) {
      toast.error(err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm("Delete this client and all related data?")) return;
    try {
      await api.deleteClient(id);
      navigate("/clients");
      toast.success("Client deleted");
    } catch (err) {
      toast.error(err.message);
    }
  };

  if (loading) return <Spinner />;
  if (error) return <ErrorMessage message={error} onRetry={load} />;

  return (
    <div className="space-y-6">
      <button onClick={() => navigate("/clients")} className="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-indigo-600">
        <ArrowLeft size={16} /> Back to Clients
      </button>

      <Card className="p-6">
        <div className="flex items-start justify-between mb-6">
          <div>
            <h2 className="text-2xl font-bold text-gray-800">{client.name}</h2>
            {client.company && <p className="text-gray-500">{client.company}</p>}
          </div>
          <div className="flex gap-2">
            <Button variant="secondary" onClick={() => setEditing(true)}><Pencil size={14} /> Edit</Button>
            <Button variant="danger" onClick={handleDelete}><Trash2 size={14} /> Delete</Button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          {[
            ["Email", client.email],
            ["Phone", client.phone],
            ["Billing Address", client.billing_address],
            ["Notes", client.notes],
          ].map(([label, value]) => (
            <div key={label}>
              <span className="text-gray-400">{label}</span>
              <p className="text-gray-700 mt-0.5">{value || "—"}</p>
            </div>
          ))}
        </div>
      </Card>

      {/* AI Summary */}
      <Card className="p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Sparkles size={18} className="text-indigo-500" />
            <h3 className="font-semibold text-gray-800">AI Client Summary</h3>
          </div>
          <Button variant="secondary" onClick={generateSummary} disabled={aiLoading}>
            {aiLoading ? <><Loader2 size={14} className="animate-spin" /> Generating...</> : <><Sparkles size={14} /> Generate Summary</>}
          </Button>
        </div>
        {aiLoading && (
          <div className="flex items-center gap-3 text-sm text-gray-500 py-4">
            <Loader2 size={18} className="animate-spin text-indigo-400" /> Analyzing client data...
          </div>
        )}
        {aiError && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-sm text-red-600">
            {aiError}
          </div>
        )}
        {aiSummary && !aiLoading && (
          <div className="bg-indigo-50 border border-indigo-100 rounded-lg p-4">
            <p className="text-sm text-gray-700 whitespace-pre-wrap">{aiSummary}</p>
            <p className="text-xs text-indigo-400 mt-3 italic">Generated by AI — review before sending</p>
          </div>
        )}
        {!aiSummary && !aiLoading && !aiError && (
          <p className="text-sm text-gray-400">Click "Generate Summary" to get an AI-powered overview of this client.</p>
        )}
      </Card>

      {/* Missions */}
      <Card>
        <div className="p-5 border-b border-gray-100 flex items-center gap-2">
          <Briefcase size={18} className="text-gray-400" />
          <h3 className="font-semibold text-gray-800">Missions ({client.missions?.length || 0})</h3>
        </div>
        {client.missions?.length > 0 ? (
          <table className="w-full text-sm">
            <thead className="text-left text-gray-500 bg-gray-50">
              <tr>
                <th className="px-5 py-2.5 font-medium">Title</th>
                <th className="px-5 py-2.5 font-medium">Amount</th>
                <th className="px-5 py-2.5 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {client.missions.map((m) => (
                <tr key={m.id} className="hover:bg-gray-50 cursor-pointer" onClick={() => navigate(`/missions/${m.id}`)}>
                  <td className="px-5 py-3 text-gray-700">{m.title}</td>
                  <td className="px-5 py-3 text-gray-700">${m.amount?.toLocaleString()}</td>
                  <td className="px-5 py-3"><StatusBadge status={m.status} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-gray-400 p-5">No missions yet</p>
        )}
      </Card>

      {/* Invoices */}
      <Card>
        <div className="p-5 border-b border-gray-100 flex items-center gap-2">
          <FileText size={18} className="text-gray-400" />
          <h3 className="font-semibold text-gray-800">Invoices ({client.invoices?.length || 0})</h3>
        </div>
        {client.invoices?.length > 0 ? (
          <table className="w-full text-sm">
            <thead className="text-left text-gray-500 bg-gray-50">
              <tr>
                <th className="px-5 py-2.5 font-medium">Number</th>
                <th className="px-5 py-2.5 font-medium">Total</th>
                <th className="px-5 py-2.5 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {client.invoices.map((inv) => (
                <tr key={inv.id} className="hover:bg-gray-50 cursor-pointer" onClick={() => navigate(`/invoices/${inv.id}`)}>
                  <td className="px-5 py-3 text-gray-700">{inv.invoice_number}</td>
                  <td className="px-5 py-3 text-gray-700">${inv.total?.toLocaleString()}</td>
                  <td className="px-5 py-3"><StatusBadge status={inv.status} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-gray-400 p-5">No invoices yet</p>
        )}
      </Card>

      {/* Edit modal */}
      <Modal open={editing} onClose={() => setEditing(false)} title="Edit Client">
        <form onSubmit={handleUpdate} className="space-y-4">
          {[
            { key: "name", label: "Name *", required: true },
            { key: "email", label: "Email", type: "email" },
            { key: "phone", label: "Phone" },
            { key: "company", label: "Company" },
          ].map(({ key, label, type, required }) => (
            <div key={key}>
              <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
              <input type={type || "text"} required={required} value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none" />
            </div>
          ))}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Billing Address</label>
            <textarea value={form.billing_address || ""} onChange={(e) => setForm({ ...form, billing_address: e.target.value })} rows={2}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
            <textarea value={form.notes || ""} onChange={(e) => setForm({ ...form, notes: e.target.value })} rows={2}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none" />
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <Button variant="secondary" type="button" onClick={() => setEditing(false)}>Cancel</Button>
            <Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save Changes"}</Button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
