/**
 * Generate a printable invoice PDF using the browser's print-to-PDF.
 * No external dependencies required.
 */
export function generateInvoicePDF(invoice) {
  const taxAmount = ((invoice.total || 0) - (invoice.subtotal || 0)).toFixed(2);

  const lineRows = (invoice.line_items || [])
    .map(
      (li) =>
        `<tr><td style="padding:8px 12px;border-bottom:1px solid #eee">${esc(li.description)}</td>
         <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:right">$${Number(li.amount).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td></tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${esc(invoice.invoice_number)}</title>
<style>
  body{font-family:Helvetica,Arial,sans-serif;color:#1a1a1a;margin:0;padding:40px}
  .header{display:flex;justify-content:space-between;margin-bottom:40px}
  .brand{font-size:24px;font-weight:700;color:#4338ca}
  .inv-num{font-size:20px;font-weight:600;color:#333}
  .meta{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:32px}
  .meta-block{font-size:13px}
  .meta-label{color:#888;text-transform:uppercase;font-size:11px;letter-spacing:0.5px;margin-bottom:4px}
  table{width:100%;border-collapse:collapse;margin-bottom:24px}
  th{text-align:left;padding:10px 12px;background:#f8f8f8;font-size:12px;text-transform:uppercase;color:#666;letter-spacing:0.5px}
  th:last-child{text-align:right}
  .totals td{padding:6px 12px;font-size:14px}
  .totals .grand{font-weight:700;font-size:16px;border-top:2px solid #333}
  .cover{background:#f5f3ff;padding:16px;border-radius:8px;font-size:13px;white-space:pre-wrap;margin-top:24px}
  .footer{margin-top:48px;text-align:center;font-size:11px;color:#aaa}
  @media print{body{padding:20px}@page{margin:15mm}}
</style></head><body>
<div class="header">
  <div>
    <div class="brand">Freelance CRM</div>
    <div style="font-size:12px;color:#888;margin-top:4px">AI-Powered CRM</div>
  </div>
  <div style="text-align:right">
    <div class="inv-num">${esc(invoice.invoice_number)}</div>
    <div style="font-size:13px;color:#666;margin-top:4px">${esc(invoice.status?.toUpperCase())}</div>
  </div>
</div>

<div class="meta">
  <div class="meta-block">
    <div class="meta-label">Bill To</div>
    <div style="font-weight:600">${esc(invoice.client_name)}</div>
  </div>
  <div class="meta-block">
    <div class="meta-label">Project</div>
    <div>${esc(invoice.mission_title)}</div>
  </div>
  <div class="meta-block">
    <div class="meta-label">Issue Date</div>
    <div>${esc(invoice.issue_date || "—")}</div>
  </div>
  <div class="meta-block">
    <div class="meta-label">Due Date</div>
    <div>${esc(invoice.due_date || "—")}</div>
  </div>
</div>

<table>
  <thead><tr><th>Description</th><th style="text-align:right">Amount</th></tr></thead>
  <tbody>${lineRows}</tbody>
</table>

<table class="totals" style="width:300px;margin-left:auto">
  <tr><td style="color:#666">Subtotal</td><td style="text-align:right">$${Number(invoice.subtotal).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td></tr>
  <tr><td style="color:#666">Tax (${invoice.tax_rate}%)</td><td style="text-align:right">$${Number(taxAmount).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td></tr>
  <tr class="grand"><td>Total</td><td style="text-align:right">$${Number(invoice.total).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td></tr>
</table>

${invoice.cover_message ? `<div class="cover"><strong style="color:#4338ca;font-size:11px;text-transform:uppercase">Cover Message</strong><br/><br/>${esc(invoice.cover_message)}</div>` : ""}

<div class="footer">Generated by Freelance CRM &middot; ${new Date().toLocaleDateString()}</div>
</body></html>`;

  const w = window.open("", "_blank");
  w.document.write(html);
  w.document.close();
  w.onload = () => w.print();
}

function esc(str) {
  if (!str) return "";
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
